-- CreateTable
CREATE TABLE `etl_adverse_events` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NOT NULL,
    `form` VARCHAR(191) NULL,
    `provider` INTEGER NULL,
    `patient_id` INTEGER NOT NULL,
    `visit_id` INTEGER NULL,
    `visit_date` DATE NULL,
    `location_id` INTEGER NULL,
    `encounter_id` INTEGER NULL,
    `obs_id` INTEGER NULL,
    `cause` INTEGER NULL,
    `adverse_event` INTEGER NULL,
    `severity` INTEGER NULL,
    `start_date` DATE NULL,
    `action_taken` INTEGER NULL,
    `voided` INTEGER NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATE NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_alcohol_drug_abuse_screening` (
    `uuid` VARCHAR(191) NOT NULL,
    `provider` INTEGER NULL,
    `patient_id` INTEGER NOT NULL,
    `visit_id` INTEGER NULL,
    `visit_date` DATE NULL,
    `location_id` INTEGER NULL,
    `encounter_id` INTEGER NULL,
    `alcohol_drinking_frequency` VARCHAR(191) NULL,
    `smoking_frequency` VARCHAR(191) NULL,
    `drugs_use_frequency` VARCHAR(191) NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATE NULL,
    `voided` INTEGER NULL,

    PRIMARY KEY (`uuid`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_allergy_chronic_illness` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NULL,
    `provider` INTEGER NULL,
    `patient_id` INTEGER NOT NULL,
    `visit_id` INTEGER NULL,
    `visit_date` DATE NULL,
    `location_id` INTEGER NULL,
    `encounter_id` INTEGER NULL,
    `obs_id` INTEGER NULL,
    `chronic_illness` INTEGER NULL,
    `chronic_illness_onset_date` DATE NULL,
    `allergy_causative_agent` INTEGER NULL,
    `allergy_reaction` INTEGER NULL,
    `allergy_severity` INTEGER NULL,
    `allergy_onset_date` DATE NULL,
    `voided` INTEGER NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATE NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_ART_preparation` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NULL,
    `patient_id` INTEGER NULL,
    `visit_id` INTEGER NULL,
    `visit_date` DATE NULL,
    `location_id` INTEGER NULL,
    `encounter_id` INTEGER NULL,
    `provider` INTEGER NULL,
    `understands_hiv_art_benefits` VARCHAR(191) NULL,
    `screened_negative_substance_abuse` VARCHAR(191) NULL,
    `screened_negative_psychiatric_illness` VARCHAR(191) NULL,
    `HIV_status_disclosure` VARCHAR(191) NULL,
    `trained_drug_admin` VARCHAR(191) NULL,
    `informed_drug_side_effects` VARCHAR(191) NULL,
    `caregiver_committed` VARCHAR(191) NULL,
    `adherance_barriers_identified` VARCHAR(191) NULL,
    `caregiver_location_contacts_known` VARCHAR(191) NULL,
    `ready_to_start_art` VARCHAR(191) NULL,
    `identified_drug_time` VARCHAR(191) NULL,
    `treatment_supporter_engaged` VARCHAR(191) NULL,
    `support_grp_meeting_awareness` VARCHAR(191) NULL,
    `enrolled_in_reminder_system` VARCHAR(191) NULL,
    `other_support_systems` VARCHAR(191) NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATE NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_ccc_defaulter_tracing` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NULL,
    `provider` INTEGER NULL,
    `patient_id` INTEGER NULL,
    `visit_id` INTEGER NULL,
    `visit_date` DATE NULL,
    `location_id` INTEGER NULL,
    `encounter_id` INTEGER NULL,
    `tracing_type` INTEGER NULL,
    `reason_for_missed_appointment` INTEGER NULL,
    `non_coded_missed_appointment_reason` VARCHAR(191) NULL,
    `tracing_outcome` INTEGER NULL,
    `attempt_number` INTEGER NULL,
    `is_final_trace` INTEGER NULL,
    `true_status` INTEGER NULL,
    `cause_of_death` INTEGER NULL,
    `comments` VARCHAR(191) NULL,
    `booking_date` DATE NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATETIME(3) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_cervical_cancer_screening` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NULL,
    `encounter_id` INTEGER NULL,
    `encounter_provider` INTEGER NULL,
    `patient_id` INTEGER NULL,
    `visit_id` INTEGER NULL,
    `visit_date` DATE NULL,
    `location_id` INTEGER NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATETIME(3) NULL,
    `visit_type` VARCHAR(191) NULL,
    `screening_type` VARCHAR(191) NULL,
    `post_treatment_complication_cause` VARCHAR(191) NULL,
    `post_treatment_complication_other` VARCHAR(191) NULL,
    `screening_method` VARCHAR(191) NULL,
    `screening_result` VARCHAR(191) NULL,
    `treatment_method` VARCHAR(191) NULL,
    `treatment_method_other` VARCHAR(191) NULL,
    `referred_out` VARCHAR(191) NULL,
    `referral_facility` VARCHAR(191) NULL,
    `referral_reason` VARCHAR(191) NULL,
    `next_appointment_date` DATE NULL,
    `voided` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_client_enrollment` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NULL,
    `client_id` INTEGER NULL,
    `visit_id` INTEGER NULL,
    `visit_date` DATE NULL,
    `encounter_id` INTEGER NULL,
    `encounter_provider` INTEGER NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATE NULL,
    `contacted_for_prevention` VARCHAR(191) NULL,
    `has_regular_free_sex_partner` VARCHAR(191) NULL,
    `year_started_sex_work` VARCHAR(191) NULL,
    `year_started_sex_with_men` VARCHAR(191) NULL,
    `year_started_drugs` VARCHAR(191) NULL,
    `has_expereienced_sexual_violence` VARCHAR(191) NULL,
    `has_expereienced_physical_violence` VARCHAR(191) NULL,
    `ever_tested_for_hiv` VARCHAR(191) NULL,
    `test_type` VARCHAR(191) NULL,
    `share_test_results` VARCHAR(191) NULL,
    `willing_to_test` VARCHAR(191) NULL,
    `test_decline_reason` VARCHAR(191) NULL,
    `receiving_hiv_care` VARCHAR(191) NULL,
    `care_facility_name` VARCHAR(191) NULL,
    `ccc_number` VARCHAR(191) NULL,
    `vl_test_done` VARCHAR(191) NULL,
    `vl_results_date` DATE NULL,
    `contact_for_appointment` VARCHAR(191) NULL,
    `contact_method` VARCHAR(191) NULL,
    `buddy_name` VARCHAR(191) NULL,
    `buddy_phone_number` VARCHAR(191) NULL,
    `voided` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_client_trace` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NULL,
    `date_created` DATETIME(3) NULL,
    `date_last_modified` DATE NULL,
    `encounter_date` DATE NULL,
    `client_id` INTEGER NULL,
    `contact_type` VARCHAR(191) NULL,
    `status` VARCHAR(191) NULL,
    `unique_patient_no` VARCHAR(191) NULL,
    `facility_linked_to` VARCHAR(191) NULL,
    `health_worker_handed_to` VARCHAR(191) NULL,
    `remarks` VARCHAR(191) NULL,
    `appointment_date` DATE NULL,
    `voided` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_clinical_visit` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NULL,
    `client_id` INTEGER NULL,
    `visit_id` INTEGER NULL,
    `visit_date` DATE NULL,
    `location_id` INTEGER NULL,
    `encounter_id` INTEGER NULL,
    `encounter_provider` INTEGER NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATE NULL,
    `implementing_partner` VARCHAR(191) NULL,
    `type_of_visit` VARCHAR(191) NULL,
    `visit_reason` VARCHAR(191) NULL,
    `service_delivery_model` VARCHAR(191) NULL,
    `sti_screened` VARCHAR(191) NULL,
    `sti_results` VARCHAR(191) NULL,
    `sti_treated` VARCHAR(191) NULL,
    `sti_referred` VARCHAR(191) NULL,
    `sti_referred_text` VARCHAR(191) NULL,
    `tb_screened` VARCHAR(191) NULL,
    `tb_results` VARCHAR(191) NULL,
    `tb_treated` VARCHAR(191) NULL,
    `tb_referred` VARCHAR(191) NULL,
    `tb_referred_text` VARCHAR(191) NULL,
    `hepatitisB_screened` VARCHAR(191) NULL,
    `hepatitisB_results` VARCHAR(191) NULL,
    `hepatitisB_treated` VARCHAR(191) NULL,
    `hepatitisB_referred` VARCHAR(191) NULL,
    `hepatitisB_text` VARCHAR(191) NULL,
    `hepatitisC_screened` VARCHAR(191) NULL,
    `hepatitisC_results` VARCHAR(191) NULL,
    `hepatitisC_treated` VARCHAR(191) NULL,
    `hepatitisC_referred` VARCHAR(191) NULL,
    `hepatitisC_text` VARCHAR(191) NULL,
    `overdose_screened` VARCHAR(191) NULL,
    `overdose_results` VARCHAR(191) NULL,
    `overdose_treated` VARCHAR(191) NULL,
    `received_naloxone` VARCHAR(191) NULL,
    `overdose_referred` VARCHAR(191) NULL,
    `overdose_text` VARCHAR(191) NULL,
    `abscess_screened` VARCHAR(191) NULL,
    `abscess_results` VARCHAR(191) NULL,
    `abscess_treated` VARCHAR(191) NULL,
    `abscess_referred` VARCHAR(191) NULL,
    `abscess_text` VARCHAR(191) NULL,
    `alcohol_screened` VARCHAR(191) NULL,
    `alcohol_results` VARCHAR(191) NULL,
    `alcohol_treated` VARCHAR(191) NULL,
    `alcohol_referred` VARCHAR(191) NULL,
    `alcohol_text` VARCHAR(191) NULL,
    `cerv_cancer_screened` VARCHAR(191) NULL,
    `cerv_cancer_results` VARCHAR(191) NULL,
    `cerv_cancer_treated` VARCHAR(191) NULL,
    `cerv_cancer_referred` VARCHAR(191) NULL,
    `cerv_cancer_text` VARCHAR(191) NULL,
    `prep_screened` VARCHAR(191) NULL,
    `prep_results` VARCHAR(191) NULL,
    `prep_treated` VARCHAR(191) NULL,
    `prep_referred` VARCHAR(191) NULL,
    `prep_text` VARCHAR(191) NULL,
    `violence_screened` VARCHAR(191) NULL,
    `violence_results` VARCHAR(191) NULL,
    `violence_treated` VARCHAR(191) NULL,
    `violence_referred` VARCHAR(191) NULL,
    `violence_text` VARCHAR(191) NULL,
    `risk_red_counselling_screened` VARCHAR(191) NULL,
    `risk_red_counselling_eligibility` VARCHAR(191) NULL,
    `risk_red_counselling_support` VARCHAR(191) NULL,
    `risk_red_counselling_ebi_provided` VARCHAR(191) NULL,
    `risk_red_counselling_text` VARCHAR(191) NULL,
    `fp_screened` VARCHAR(191) NULL,
    `fp_eligibility` VARCHAR(191) NULL,
    `fp_treated` VARCHAR(191) NULL,
    `fp_referred` VARCHAR(191) NULL,
    `fp_text` VARCHAR(191) NULL,
    `mental_health_screened` VARCHAR(191) NULL,
    `mental_health_results` VARCHAR(191) NULL,
    `mental_health_support` VARCHAR(191) NULL,
    `mental_health_referred` VARCHAR(191) NULL,
    `mental_health_text` VARCHAR(191) NULL,
    `hiv_self_rep_status` VARCHAR(191) NULL,
    `last_hiv_test_setting` VARCHAR(191) NULL,
    `counselled_for_hiv` VARCHAR(191) NULL,
    `hiv_tested` VARCHAR(191) NULL,
    `test_frequency` VARCHAR(191) NULL,
    `received_results` VARCHAR(191) NULL,
    `test_results` VARCHAR(191) NULL,
    `linked_to_art` VARCHAR(191) NULL,
    `facility_linked_to` VARCHAR(191) NULL,
    `self_test_education` VARCHAR(191) NULL,
    `self_test_kits_given` VARCHAR(191) NULL,
    `self_use_kits` VARCHAR(191) NULL,
    `distribution_kits` VARCHAR(191) NULL,
    `self_tested` VARCHAR(191) NULL,
    `self_test_date` DATE NULL,
    `self_test_frequency` VARCHAR(191) NULL,
    `self_test_results` VARCHAR(191) NULL,
    `test_confirmatory_results` VARCHAR(191) NULL,
    `confirmatory_facility` VARCHAR(191) NULL,
    `self_test_linked_art` VARCHAR(191) NULL,
    `self_test_link_facility` VARCHAR(191) NULL,
    `hiv_care_facility` VARCHAR(191) NULL,
    `other_hiv_care_facility` VARCHAR(191) NULL,
    `initiated_art_this_month` VARCHAR(191) NULL,
    `active_art` VARCHAR(191) NULL,
    `eligible_vl` VARCHAR(191) NULL,
    `vl_test_done` VARCHAR(191) NULL,
    `vl_results` VARCHAR(191) NULL,
    `received_vl_results` VARCHAR(191) NULL,
    `condom_use_education` VARCHAR(191) NULL,
    `post_abortal_care` VARCHAR(191) NULL,
    `linked_to_psychosocial` VARCHAR(191) NULL,
    `male_condoms_no` VARCHAR(191) NULL,
    `female_condoms_no` VARCHAR(191) NULL,
    `lubes_no` VARCHAR(191) NULL,
    `syringes_needles_no` VARCHAR(191) NULL,
    `pep_eligible` VARCHAR(191) NULL,
    `exposure_type` VARCHAR(191) NULL,
    `other_exposure_type` VARCHAR(191) NULL,
    `clinical_notes` VARCHAR(191) NULL,
    `appointment_date` DATE NULL,
    `voided` INTEGER NULL,

    PRIMARY KEY (`id`)
) ENGINE=MyISAM CHARACTER SET latin1;

-- CreateTable
CREATE TABLE `etl_contact` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NULL,
    `unique_identifier` VARCHAR(191) NULL,
    `client_id` INTEGER NULL,
    `visit_id` INTEGER NULL,
    `visit_date` DATE NULL,
    `location_id` INTEGER NULL,
    `encounter_id` INTEGER NULL,
    `encounter_provider` INTEGER NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATE NULL,
    `key_population_type` VARCHAR(191) NULL,
    `contacted_by_peducator` VARCHAR(191) NULL,
    `program_name` VARCHAR(191) NULL,
    `frequent_hotspot_name` VARCHAR(191) NULL,
    `frequent_hotspot_type` VARCHAR(191) NULL,
    `year_started_sex_work` VARCHAR(191) NULL,
    `year_started_sex_with_men` VARCHAR(191) NULL,
    `year_started_drugs` VARCHAR(191) NULL,
    `avg_weekly_sex_acts` INTEGER NULL,
    `avg_weekly_anal_sex_acts` INTEGER NULL,
    `avg_daily_drug_injections` INTEGER NULL,
    `contact_person_name` VARCHAR(191) NULL,
    `contact_person_alias` VARCHAR(191) NULL,
    `contact_person_phone` VARCHAR(191) NULL,
    `voided` INTEGER NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_contacts_linked` (
    `id_auto` INTEGER NOT NULL AUTO_INCREMENT,
    `id` INTEGER NULL,
    `patient_id` INTEGER NULL,
    `relationship_type` INTEGER NULL,
    `baseline_hiv_status` VARCHAR(191) NULL,
    `visit_date` DATE NULL,
    `final_test_result` VARCHAR(191) NULL,

    PRIMARY KEY (`id_auto`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_covid19_assessment` (
    `id_auto` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NULL,
    `provider` INTEGER NULL,
    `patient_id` INTEGER NULL,
    `visit_id` INTEGER NULL,
    `visit_date` VARCHAR(191) NULL,
    `location_id` INTEGER NULL,
    `encounter_id` INTEGER NULL,
    `obs_id` VARCHAR(191) NULL,
    `ever_vaccinated` VARCHAR(191) NULL,
    `first_vaccine_type` VARCHAR(191) NULL,
    `second_vaccine_type` VARCHAR(191) NULL,
    `first_dose` VARCHAR(191) NULL,
    `second_dose` VARCHAR(191) NULL,
    `first_dose_date` VARCHAR(191) NULL,
    `second_dose_date` VARCHAR(191) NULL,
    `first_vaccination_verified` VARCHAR(191) NULL,
    `second_vaccination_verified` VARCHAR(191) NULL,
    `final_vaccination_status` VARCHAR(191) NULL,
    `ever_received_booster` VARCHAR(191) NULL,
    `booster_vaccine_taken` VARCHAR(191) NULL,
    `date_taken_booster_vaccine` VARCHAR(191) NULL,
    `booster_sequence` VARCHAR(191) NULL,
    `booster_dose_verified` VARCHAR(191) NULL,
    `ever_tested_covid_19_positive` VARCHAR(191) NULL,
    `symptomatic` VARCHAR(191) NULL,
    `date_tested_positive` VARCHAR(191) NULL,
    `hospital_admission` VARCHAR(191) NULL,
    `admission_unit` VARCHAR(191) NULL,
    `on_ventillator` VARCHAR(191) NULL,
    `on_oxygen_supplement` VARCHAR(191) NULL,
    `date_created` DATE NULL,
    `date_last_modified` DATE NULL,
    `voided` INTEGER NULL,

    PRIMARY KEY (`id_auto`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Link` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `description` VARCHAR(191) NOT NULL,
    `url` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `EtlPatientProgram` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `uuid` VARCHAR(191) NOT NULL,
    `patient_id` INTEGER NOT NULL,
    `location_id` INTEGER NOT NULL,
    `program` VARCHAR(191) NOT NULL,
    `date_enrolled` VARCHAR(191) NOT NULL,
    `date_completed` VARCHAR(191) NOT NULL,
    `outcome` VARCHAR(191) NOT NULL,
    `date_created` VARCHAR(191) NOT NULL,
    `date_last_modified` VARCHAR(191) NOT NULL,
    `voided` VARCHAR(191) NOT NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `etl_current_in_care` (
    `patient_id` INTEGER NOT NULL,
    `dob` DATE NULL,
    `gender` VARCHAR(191) NULL,
    `enroll_date` DATE NULL,
    `latest_enrolment_date` VARCHAR(191) NOT NULL,
    `latest_vis_date` VARCHAR(191) NOT NULL,
    `latest_tca` VARCHAR(191) NOT NULL,
    `stability` VARCHAR(191) NOT NULL,
    `disc_patient` INTEGER NULL,
    `effective_disc_date` DATE NULL,
    `date_discontinued` DATE NULL,
    `started_on_drugs` INTEGER NULL,

    PRIMARY KEY (`patient_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `ETLHtsTest` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `visit_id` INTEGER NOT NULL,
    `patient_id` INTEGER NOT NULL,
    `encounter_id` INTEGER NOT NULL,
    `encounter_uuid` VARCHAR(191) NOT NULL,
    `encounter_location` INTEGER NOT NULL,
    `creator` VARCHAR(191) NOT NULL,
    `date_created` VARCHAR(191) NOT NULL,
    `date_last_modified` VARCHAR(191) NOT NULL,
    `visit_date` VARCHAR(191) NOT NULL,
    `test_type` VARCHAR(191) NOT NULL,
    `population_type` VARCHAR(191) NOT NULL,
    `key_population_type` VARCHAR(191) NOT NULL,
    `ever_tested_for_hiv` VARCHAR(191) NOT NULL,
    `months_since_last_test` VARCHAR(191) NOT NULL,
    `patient_disabled` VARCHAR(191) NOT NULL,
    `disability_type` VARCHAR(191) NOT NULL,
    `patient_consented` VARCHAR(191) NOT NULL,
    `client_tested_as` VARCHAR(191) NOT NULL,
    `setting` VARCHAR(191) NOT NULL,
    `approach` VARCHAR(191) NOT NULL,
    `test_strategy` VARCHAR(191) NOT NULL,
    `hts_entry_point` VARCHAR(191) NOT NULL,
    `test_1_kit_name` VARCHAR(191) NOT NULL,
    `test_1_kit_lot_no` VARCHAR(191) NOT NULL,
    `test_1_kit_expiry` VARCHAR(191) NOT NULL,
    `test_1_result` VARCHAR(191) NOT NULL,
    `test_2_kit_name` VARCHAR(191) NOT NULL,
    `test_2_kit_lot_no` VARCHAR(191) NOT NULL,
    `test_2_kit_expiry` VARCHAR(191) NOT NULL,
    `test_2_result` VARCHAR(191) NOT NULL,
    `final_test_result` VARCHAR(191) NOT NULL,
    `syphillis_test_result` VARCHAR(191) NOT NULL,
    `patient_given_result` VARCHAR(191) NOT NULL,
    `couple_discordant` VARCHAR(191) NOT NULL,
    `referral_for` VARCHAR(191) NOT NULL,
    `referral_facility` VARCHAR(191) NOT NULL,
    `other_referral_facility` VARCHAR(191) NOT NULL,
    `neg_referral_for` VARCHAR(191) NOT NULL,
    `neg_referral_specify` VARCHAR(191) NOT NULL,
    `tb_screening` VARCHAR(191) NOT NULL,
    `patient_had_hiv_self_test` VARCHAR(191) NOT NULL,
    `remarks` VARCHAR(191) NOT NULL,
    `voided` VARCHAR(191) NOT NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
