/**
 * This file was generated by Nexus Schema
 * Do not make changes to this file directly
 */


import type { Context } from "./src/context"




declare global {
  interface NexusGen extends NexusGenTypes {}
}

export interface NexusGenInputs {
}

export interface NexusGenEnums {
}

export interface NexusGenScalars {
  String: string
  Int: number
  Float: number
  Boolean: boolean
  ID: string
}

export interface NexusGenObjects {
  ARTPreparation: { // root type
    HIV_status_disclosure?: string | null; // String
    adherance_barriers_identified?: string | null; // String
    caregiver_location_contacts_known?: string | null; // String
    date_created?: number | null; // Int
    date_last_modified?: number | null; // Int
    encounter_id?: number | null; // Int
    enrolled_in_reminder_system?: string | null; // String
    identified_drug_time?: string | null; // String
    informed_drug_side_effects?: string | null; // String
    location_id?: number | null; // Int
    mfl_code?: number | null; // Int
    other_support_systems?: string | null; // String
    patient_id?: number | null; // Int
    provider?: number | null; // Int
    ready_to_start_art?: string | null; // String
    screened_negative_psychiatric_illness?: string | null; // String
    screened_negative_substance_abuse?: string | null; // String
    support_grp_meeting_awareness?: string | null; // String
    trained_drug_admin?: string | null; // String
    treatment_supporter_engaged?: string | null; // String
    understands_hiv_art_benefits?: string | null; // String
    uuid?: string | null; // String
    visit_date?: string | null; // String
    visit_id?: number | null; // Int
    voided?: number | null; // Int
  }
  AdverseEvents: { // root type
    adverse_event?: number | null; // Int
    cause?: number | null; // Int
    date_created?: number | null; // Int
    date_last_modified?: number | null; // Int
    encounter_id?: number | null; // Int
    form?: string | null; // String
    location_id?: number | null; // Int
    mfl_code?: number | null; // Int
    obs_id?: number | null; // Int
    patient_id?: number | null; // Int
    provider?: number | null; // Int
    severity?: number | null; // Int
    start_date?: string | null; // String
    uuid?: string | null; // String
    visit_date?: string | null; // String
    visit_id?: number | null; // Int
    voided?: number | null; // Int
  }
  AlcoholDrugAbuseScreening: { // root type
    alcohol_drinking_frequency?: string | null; // String
    date_created?: number | null; // Int
    date_last_modified?: number | null; // Int
    drugs_use_frequency?: string | null; // String
    encounter_id?: number | null; // Int
    location_id?: number | null; // Int
    mfl_code?: number | null; // Int
    patient_id?: number | null; // Int
    provider?: number | null; // Int
    smoking_frequency?: string | null; // String
    uuid?: string | null; // String
    visit_date?: string | null; // String
    visit_id?: number | null; // Int
    voided?: number | null; // Int
  }
  AllergyChronicIllness: { // root type
    allergy_causative_agent?: string | null; // String
    allergy_onset_date?: string | null; // String
    allergy_reaction?: number | null; // Int
    allergy_severity?: number | null; // Int
    chronic_illness?: number | null; // Int
    chronic_illness_onset_date?: string | null; // String
    date_created?: number | null; // Int
    date_last_modified?: number | null; // Int
    encounter_id?: number | null; // Int
    location_id?: number | null; // Int
    mfl_code?: number | null; // Int
    obs_id?: number | null; // Int
    patient_id?: number | null; // Int
    provider?: number | null; // Int
    uuid?: string | null; // String
    visit_date?: string | null; // String
    visit_id?: number | null; // Int
    voided?: number | null; // Int
  }
  CccDefaulterTracing: { // root type
    attempt_number?: number | null; // Int
    booking_date?: string | null; // String
    cause_of_death?: number | null; // Int
    comments?: string | null; // String
    date_created?: number | null; // Int
    date_last_modified?: number | null; // Int
    encounter_id?: number | null; // Int
    fml_code?: number | null; // Int
    is_final_trace?: number | null; // Int
    location_id?: number | null; // Int
    mfl_code?: number | null; // Int
    non_coded_missed_appointment_reason?: string | null; // String
    patient_id?: number | null; // Int
    provider?: number | null; // Int
    reason_for_missed_appointment?: number | null; // Int
    tracing_outcome?: number | null; // Int
    tracing_type?: number | null; // Int
    true_status?: number | null; // Int
    uuid?: string | null; // String
    visit_date?: string | null; // String
    visit_id?: number | null; // Int
  }
  CervicalCancerScreening: { // root type
    booking_date?: string | null; // String
    date_last_modified?: string | null; // String
    encounter_id?: number | null; // Int
    encounter_provider?: number | null; // Int
    location_id?: number | null; // Int
    mfl_code?: number | null; // Int
    patient_id?: number | null; // Int
    post_treatment_complication_cause?: string | null; // String
    provider?: number | null; // Int
    referral_facility?: string | null; // String
    referral_reason?: string | null; // String
    referred_out?: string | null; // String
    screening_method?: string | null; // String
    screening_result?: string | null; // String
    screening_type?: string | null; // String
    treatment_method?: string | null; // String
    treatment_method_other?: string | null; // String
    uuid?: string | null; // String
    visit_date?: string | null; // String
    visit_id?: number | null; // Int
    visit_type?: string | null; // String
    voided?: number | null; // Int
  }
  ClientEnrollment: { // root type
    buddy_name?: string | null; // String
    buddy_phone_number?: string | null; // String
    care_facility_name?: string | null; // String
    ccc_number?: string | null; // String
    client_id?: number | null; // Int
    contact_for_appointment?: string | null; // String
    contact_method?: string | null; // String
    contacted_for_prevention?: string | null; // String
    date_last_modified?: string | null; // String
    encounter_id?: number | null; // Int
    encounter_provider?: number | null; // Int
    ever_tested_for_hiv?: string | null; // String
    fml_code?: number | null; // Int
    has_expereienced_physical_violence?: string | null; // String
    has_expereienced_sexual_violence?: string | null; // String
    has_regular_free_sex_partner?: string | null; // String
    location_id?: number | null; // Int
    mfl_code?: number | null; // Int
    receiving_hiv_care?: string | null; // String
    share_test_results?: string | null; // String
    test_decline_reason?: string | null; // String
    test_type?: string | null; // String
    uuid?: string | null; // String
    visit_date?: string | null; // String
    visit_id?: number | null; // Int
    vl_results_date?: string | null; // String
    vl_test_done?: string | null; // String
    voided?: number | null; // Int
    willing_to_test?: string | null; // String
    year_started_drugs?: string | null; // String
    year_started_sex_with_men?: string | null; // String
  }
  ClientTrace: { // root type
    appointment_date?: number | null; // Int
    client_id?: number | null; // Int
    contact_type?: string | null; // String
    date_created?: number | null; // Int
    date_last_modified?: number | null; // Int
    encounter_date?: string | null; // String
    facility_linked_to?: number | null; // Int
    health_worker_handed_to?: string | null; // String
    mfl_code?: number | null; // Int
    remarks?: number | null; // Int
    status?: string | null; // String
    unique_patient_no?: string | null; // String
    uuid?: string | null; // String
  }
  ClinicalVisit: { // root type
    abscess_referred?: string | null; // String
    abscess_results?: string | null; // String
    abscess_screened?: string | null; // String
    abscess_text?: string | null; // String
    abscess_treated?: string | null; // String
    active_art?: string | null; // String
    alcohol_referred?: string | null; // String
    alcohol_results?: string | null; // String
    alcohol_screened?: string | null; // String
    alcohol_text?: string | null; // String
    alcohol_treated?: string | null; // String
    appointment_date?: string | null; // String
    cerv_cancer_referred?: string | null; // String
    cerv_cancer_results?: string | null; // String
    cerv_cancer_screened?: string | null; // String
    cerv_cancer_text?: string | null; // String
    cerv_cancer_treated?: string | null; // String
    client_id?: number | null; // Int
    clinical_notes?: string | null; // String
    condom_use_education?: string | null; // String
    confirmatory_facility?: string | null; // String
    counselled_for_hiv?: string | null; // String
    date_created?: string | null; // String
    date_last_modified?: string | null; // String
    distribution_kits?: string | null; // String
    eligible_vl?: string | null; // String
    encounter_id?: number | null; // Int
    encounter_provider?: number | null; // Int
    exposure_type?: string | null; // String
    facility_linked_to?: string | null; // String
    female_condoms_no?: string | null; // String
    fp_eligibility?: string | null; // String
    fp_referred?: string | null; // String
    fp_screened?: string | null; // String
    fp_text?: string | null; // String
    fp_treated?: string | null; // String
    hepatitisB_referred?: string | null; // String
    hepatitisB_results?: string | null; // String
    hepatitisB_screened?: string | null; // String
    hepatitisB_text?: string | null; // String
    hepatitisB_treated?: string | null; // String
    hepatitisC_referred?: string | null; // String
    hepatitisC_results?: string | null; // String
    hepatitisC_screened?: string | null; // String
    hepatitisC_text?: string | null; // String
    hepatitisC_treated?: string | null; // String
    hiv_care_facility?: string | null; // String
    hiv_self_rep_status?: string | null; // String
    hiv_tested?: string | null; // String
    implementing_partner?: string | null; // String
    initiated_art_this_month?: string | null; // String
    last_hiv_test_setting?: string | null; // String
    linked_to_art?: string | null; // String
    linked_to_psychosocial?: string | null; // String
    location_id?: number | null; // Int
    lubes_no?: string | null; // String
    male_condoms_no?: string | null; // String
    mental_health_referred?: string | null; // String
    mental_health_results?: string | null; // String
    mental_health_screened?: string | null; // String
    mental_health_support?: string | null; // String
    mental_health_text?: string | null; // String
    mfl_code?: number | null; // Int
    offsite_confirmatory_facility?: string | null; // String
    other_exposure_type?: string | null; // String
    other_hiv_care_facility?: string | null; // String
    overdose_referred?: string | null; // String
    overdose_results?: string | null; // String
    overdose_screened?: string | null; // String
    overdose_text?: string | null; // String
    overdose_treated?: string | null; // String
    pep_eligible?: string | null; // String
    post_abortal_care?: string | null; // String
    prep_referred?: string | null; // String
    prep_results?: string | null; // String
    prep_screened?: string | null; // String
    prep_text?: string | null; // String
    prep_treated?: string | null; // String
    received_naloxone?: string | null; // String
    received_results?: string | null; // String
    received_vl_results?: string | null; // String
    risk_red_counselling_ebi_provided?: string | null; // String
    risk_red_counselling_eligibility?: string | null; // String
    risk_red_counselling_screened?: string | null; // String
    risk_red_counselling_support?: string | null; // String
    risk_red_counselling_text?: string | null; // String
    self_test_date?: string | null; // String
    self_test_education?: string | null; // String
    self_test_frequency?: string | null; // String
    self_test_kits_given?: string | null; // String
    self_test_link_facility?: string | null; // String
    self_test_linked_art?: string | null; // String
    self_test_results?: string | null; // String
    self_tested?: string | null; // String
    self_use_kits?: string | null; // String
    service_delivery_model?: string | null; // String
    sti_referred?: string | null; // String
    sti_referred_text?: string | null; // String
    sti_results?: string | null; // String
    sti_screened?: string | null; // String
    sti_treated?: string | null; // String
    syringes_needles_no?: string | null; // String
    tb_referred?: string | null; // String
    tb_referred_text?: string | null; // String
    tb_results?: string | null; // String
    tb_screened?: string | null; // String
    tb_treated?: string | null; // String
    test_confirmatory_results?: string | null; // String
    test_frequency?: string | null; // String
    test_results?: string | null; // String
    type_of_visit?: string | null; // String
    uuid?: string | null; // String
    violence_referred?: string | null; // String
    violence_results?: string | null; // String
    violence_screened?: string | null; // String
    violence_text?: string | null; // String
    violence_treated?: string | null; // String
    visit_date?: string | null; // String
    visit_id?: number | null; // Int
    visit_reason?: string | null; // String
    vl_results?: string | null; // String
    vl_test_done?: string | null; // String
    voided?: number | null; // Int
  }
  ContactsLinked: { // root type
    baseline_hiv_status?: string | null; // String
    final_test_result?: string | null; // String
    patient_id?: number | null; // Int
    relationship_type?: number | null; // Int
    visit_date?: string | null; // String
  }
  Covid19Assessment: { // root type
    admission_unit?: string | null; // String
    booster_dose_verified?: string | null; // String
    booster_sequence?: string | null; // String
    booster_vaccine_taken?: string | null; // String
    date_created?: string | null; // String
    date_last_modified?: string | null; // String
    date_taken_booster_vaccine?: string | null; // String
    date_tested_positive?: string | null; // String
    encounter_id?: number | null; // Int
    ever_received_booster?: string | null; // String
    ever_tested_covid_19_positive?: string | null; // String
    ever_vaccinated?: string | null; // String
    final_vaccination_status?: string | null; // String
    first_dose?: string | null; // String
    first_dose_date?: string | null; // String
    first_vaccination_verified?: string | null; // String
    first_vaccine_type?: string | null; // String
    hospital_admission?: string | null; // String
    location_id?: number | null; // Int
    mfl_code?: number | null; // Int
    obs_id?: string | null; // String
    on_oxygen_supplement?: string | null; // String
    on_ventillator?: string | null; // String
    patient_id?: number | null; // Int
    provider?: number | null; // Int
    second_dose?: string | null; // String
    second_dose_date?: string | null; // String
    second_vaccination_verified?: string | null; // String
    second_vaccine_type?: string | null; // String
    symptomatic?: string | null; // String
    uuid?: string | null; // String
    visit_date?: string | null; // String
    visit_id?: number | null; // Int
    voided?: number | null; // Int
  }
  ETLHtsTest: { // root type
    approach: string; // String!
    client_tested_as: string; // String!
    couple_discordant: string; // String!
    creator: string; // String!
    date_created: string; // String!
    date_last_modified: string; // String!
    disability_type: string; // String!
    encounter_id: number; // Int!
    encounter_location: number; // Int!
    encounter_uuid: string; // String!
    ever_tested_for_hiv: string; // String!
    final_test_result: string; // String!
    fml_code: number; // Int!
    hts_entry_point: string; // String!
    id: number; // Int!
    months_since_last_test: string; // String!
    neg_referral_for: string; // String!
    neg_referral_specify: string; // String!
    other_referral_facility: string; // String!
    patient_consented: string; // String!
    patient_disabled: string; // String!
    patient_given_result: string; // String!
    patient_had_hiv_self_test: string; // String!
    patient_id: number; // Int!
    population_type: string; // String!
    referral_facility: string; // String!
    referral_for: string; // String!
    remarks: string; // String!
    setting: string; // String!
    syphillis_test_result: string; // String!
    tb_screening: string; // String!
    test_1_kit_expiry: string; // String!
    test_1_kit_lot_no: string; // String!
    test_1_kit_name: string; // String!
    test_1_result: string; // String!
    test_2_kit_expiry: string; // String!
    test_2_kit_lot_no: string; // String!
    test_2_kit_name: string; // String!
    test_2_result: string; // String!
    test_strategy: string; // String!
    test_type: string; // String!
    visit_date: string; // String!
    visit_id: number; // Int!
    voided: string; // String!
  }
  EtlCurrentInCare: { // root type
    date_discontinued?: string | null; // String
    disc_patient?: string | null; // String
    dob?: string | null; // String
    effective_disc_date?: string | null; // String
    enroll_date?: string | null; // String
    gender?: string | null; // String
    latest_enrolment_date?: string | null; // String
    latest_tca?: string | null; // String
    latest_vis_date?: string | null; // String
    mfl_code?: number | null; // Int
    patient_id?: number | null; // Int
    stability?: string | null; // String
    started_on_drugs?: number | null; // Int
  }
  EtlPatientProgram: { // root type
    date_completed: string; // String!
    date_created: string; // String!
    date_enrolled: string; // String!
    date_last_modified: string; // String!
    fml_code: number; // Int!
    id: number; // Int!
    location_id: number; // Int!
    outcome: string; // String!
    patient_id: number; // Int!
    program: string; // String!
    uuid: string; // String!
    voided: string; // String!
  }
  Mutation: {};
  Query: {};
}

export interface NexusGenInterfaces {
}

export interface NexusGenUnions {
}

export type NexusGenRootTypes = NexusGenObjects

export type NexusGenAllTypes = NexusGenRootTypes & NexusGenScalars

export interface NexusGenFieldTypes {
  ARTPreparation: { // field return type
    HIV_status_disclosure: string | null; // String
    adherance_barriers_identified: string | null; // String
    caregiver_location_contacts_known: string | null; // String
    date_created: number | null; // Int
    date_last_modified: number | null; // Int
    encounter_id: number | null; // Int
    enrolled_in_reminder_system: string | null; // String
    identified_drug_time: string | null; // String
    informed_drug_side_effects: string | null; // String
    location_id: number | null; // Int
    mfl_code: number | null; // Int
    other_support_systems: string | null; // String
    patient_id: number | null; // Int
    provider: number | null; // Int
    ready_to_start_art: string | null; // String
    screened_negative_psychiatric_illness: string | null; // String
    screened_negative_substance_abuse: string | null; // String
    support_grp_meeting_awareness: string | null; // String
    trained_drug_admin: string | null; // String
    treatment_supporter_engaged: string | null; // String
    understands_hiv_art_benefits: string | null; // String
    uuid: string | null; // String
    visit_date: string | null; // String
    visit_id: number | null; // Int
    voided: number | null; // Int
  }
  AdverseEvents: { // field return type
    adverse_event: number | null; // Int
    cause: number | null; // Int
    date_created: number | null; // Int
    date_last_modified: number | null; // Int
    encounter_id: number | null; // Int
    form: string | null; // String
    location_id: number | null; // Int
    mfl_code: number | null; // Int
    obs_id: number | null; // Int
    patient_id: number | null; // Int
    provider: number | null; // Int
    severity: number | null; // Int
    start_date: string | null; // String
    uuid: string | null; // String
    visit_date: string | null; // String
    visit_id: number | null; // Int
    voided: number | null; // Int
  }
  AlcoholDrugAbuseScreening: { // field return type
    alcohol_drinking_frequency: string | null; // String
    date_created: number | null; // Int
    date_last_modified: number | null; // Int
    drugs_use_frequency: string | null; // String
    encounter_id: number | null; // Int
    location_id: number | null; // Int
    mfl_code: number | null; // Int
    patient_id: number | null; // Int
    provider: number | null; // Int
    smoking_frequency: string | null; // String
    uuid: string | null; // String
    visit_date: string | null; // String
    visit_id: number | null; // Int
    voided: number | null; // Int
  }
  AllergyChronicIllness: { // field return type
    allergy_causative_agent: string | null; // String
    allergy_onset_date: string | null; // String
    allergy_reaction: number | null; // Int
    allergy_severity: number | null; // Int
    chronic_illness: number | null; // Int
    chronic_illness_onset_date: string | null; // String
    date_created: number | null; // Int
    date_last_modified: number | null; // Int
    encounter_id: number | null; // Int
    location_id: number | null; // Int
    mfl_code: number | null; // Int
    obs_id: number | null; // Int
    patient_id: number | null; // Int
    provider: number | null; // Int
    uuid: string | null; // String
    visit_date: string | null; // String
    visit_id: number | null; // Int
    voided: number | null; // Int
  }
  CccDefaulterTracing: { // field return type
    attempt_number: number | null; // Int
    booking_date: string | null; // String
    cause_of_death: number | null; // Int
    comments: string | null; // String
    date_created: number | null; // Int
    date_last_modified: number | null; // Int
    encounter_id: number | null; // Int
    fml_code: number | null; // Int
    is_final_trace: number | null; // Int
    location_id: number | null; // Int
    mfl_code: number | null; // Int
    non_coded_missed_appointment_reason: string | null; // String
    patient_id: number | null; // Int
    provider: number | null; // Int
    reason_for_missed_appointment: number | null; // Int
    tracing_outcome: number | null; // Int
    tracing_type: number | null; // Int
    true_status: number | null; // Int
    uuid: string | null; // String
    visit_date: string | null; // String
    visit_id: number | null; // Int
  }
  CervicalCancerScreening: { // field return type
    booking_date: string | null; // String
    date_last_modified: string | null; // String
    encounter_id: number | null; // Int
    encounter_provider: number | null; // Int
    location_id: number | null; // Int
    mfl_code: number | null; // Int
    patient_id: number | null; // Int
    post_treatment_complication_cause: string | null; // String
    provider: number | null; // Int
    referral_facility: string | null; // String
    referral_reason: string | null; // String
    referred_out: string | null; // String
    screening_method: string | null; // String
    screening_result: string | null; // String
    screening_type: string | null; // String
    treatment_method: string | null; // String
    treatment_method_other: string | null; // String
    uuid: string | null; // String
    visit_date: string | null; // String
    visit_id: number | null; // Int
    visit_type: string | null; // String
    voided: number | null; // Int
  }
  ClientEnrollment: { // field return type
    buddy_name: string | null; // String
    buddy_phone_number: string | null; // String
    care_facility_name: string | null; // String
    ccc_number: string | null; // String
    client_id: number | null; // Int
    contact_for_appointment: string | null; // String
    contact_method: string | null; // String
    contacted_for_prevention: string | null; // String
    date_last_modified: string | null; // String
    encounter_id: number | null; // Int
    encounter_provider: number | null; // Int
    ever_tested_for_hiv: string | null; // String
    fml_code: number | null; // Int
    has_expereienced_physical_violence: string | null; // String
    has_expereienced_sexual_violence: string | null; // String
    has_regular_free_sex_partner: string | null; // String
    location_id: number | null; // Int
    mfl_code: number | null; // Int
    receiving_hiv_care: string | null; // String
    share_test_results: string | null; // String
    test_decline_reason: string | null; // String
    test_type: string | null; // String
    uuid: string | null; // String
    visit_date: string | null; // String
    visit_id: number | null; // Int
    vl_results_date: string | null; // String
    vl_test_done: string | null; // String
    voided: number | null; // Int
    willing_to_test: string | null; // String
    year_started_drugs: string | null; // String
    year_started_sex_with_men: string | null; // String
  }
  ClientTrace: { // field return type
    appointment_date: number | null; // Int
    client_id: number | null; // Int
    contact_type: string | null; // String
    date_created: number | null; // Int
    date_last_modified: number | null; // Int
    encounter_date: string | null; // String
    facility_linked_to: number | null; // Int
    health_worker_handed_to: string | null; // String
    mfl_code: number | null; // Int
    remarks: number | null; // Int
    status: string | null; // String
    unique_patient_no: string | null; // String
    uuid: string | null; // String
  }
  ClinicalVisit: { // field return type
    abscess_referred: string | null; // String
    abscess_results: string | null; // String
    abscess_screened: string | null; // String
    abscess_text: string | null; // String
    abscess_treated: string | null; // String
    active_art: string | null; // String
    alcohol_referred: string | null; // String
    alcohol_results: string | null; // String
    alcohol_screened: string | null; // String
    alcohol_text: string | null; // String
    alcohol_treated: string | null; // String
    appointment_date: string | null; // String
    cerv_cancer_referred: string | null; // String
    cerv_cancer_results: string | null; // String
    cerv_cancer_screened: string | null; // String
    cerv_cancer_text: string | null; // String
    cerv_cancer_treated: string | null; // String
    client_id: number | null; // Int
    clinical_notes: string | null; // String
    condom_use_education: string | null; // String
    confirmatory_facility: string | null; // String
    counselled_for_hiv: string | null; // String
    date_created: string | null; // String
    date_last_modified: string | null; // String
    distribution_kits: string | null; // String
    eligible_vl: string | null; // String
    encounter_id: number | null; // Int
    encounter_provider: number | null; // Int
    exposure_type: string | null; // String
    facility_linked_to: string | null; // String
    female_condoms_no: string | null; // String
    fp_eligibility: string | null; // String
    fp_referred: string | null; // String
    fp_screened: string | null; // String
    fp_text: string | null; // String
    fp_treated: string | null; // String
    hepatitisB_referred: string | null; // String
    hepatitisB_results: string | null; // String
    hepatitisB_screened: string | null; // String
    hepatitisB_text: string | null; // String
    hepatitisB_treated: string | null; // String
    hepatitisC_referred: string | null; // String
    hepatitisC_results: string | null; // String
    hepatitisC_screened: string | null; // String
    hepatitisC_text: string | null; // String
    hepatitisC_treated: string | null; // String
    hiv_care_facility: string | null; // String
    hiv_self_rep_status: string | null; // String
    hiv_tested: string | null; // String
    implementing_partner: string | null; // String
    initiated_art_this_month: string | null; // String
    last_hiv_test_setting: string | null; // String
    linked_to_art: string | null; // String
    linked_to_psychosocial: string | null; // String
    location_id: number | null; // Int
    lubes_no: string | null; // String
    male_condoms_no: string | null; // String
    mental_health_referred: string | null; // String
    mental_health_results: string | null; // String
    mental_health_screened: string | null; // String
    mental_health_support: string | null; // String
    mental_health_text: string | null; // String
    mfl_code: number | null; // Int
    offsite_confirmatory_facility: string | null; // String
    other_exposure_type: string | null; // String
    other_hiv_care_facility: string | null; // String
    overdose_referred: string | null; // String
    overdose_results: string | null; // String
    overdose_screened: string | null; // String
    overdose_text: string | null; // String
    overdose_treated: string | null; // String
    pep_eligible: string | null; // String
    post_abortal_care: string | null; // String
    prep_referred: string | null; // String
    prep_results: string | null; // String
    prep_screened: string | null; // String
    prep_text: string | null; // String
    prep_treated: string | null; // String
    received_naloxone: string | null; // String
    received_results: string | null; // String
    received_vl_results: string | null; // String
    risk_red_counselling_ebi_provided: string | null; // String
    risk_red_counselling_eligibility: string | null; // String
    risk_red_counselling_screened: string | null; // String
    risk_red_counselling_support: string | null; // String
    risk_red_counselling_text: string | null; // String
    self_test_date: string | null; // String
    self_test_education: string | null; // String
    self_test_frequency: string | null; // String
    self_test_kits_given: string | null; // String
    self_test_link_facility: string | null; // String
    self_test_linked_art: string | null; // String
    self_test_results: string | null; // String
    self_tested: string | null; // String
    self_use_kits: string | null; // String
    service_delivery_model: string | null; // String
    sti_referred: string | null; // String
    sti_referred_text: string | null; // String
    sti_results: string | null; // String
    sti_screened: string | null; // String
    sti_treated: string | null; // String
    syringes_needles_no: string | null; // String
    tb_referred: string | null; // String
    tb_referred_text: string | null; // String
    tb_results: string | null; // String
    tb_screened: string | null; // String
    tb_treated: string | null; // String
    test_confirmatory_results: string | null; // String
    test_frequency: string | null; // String
    test_results: string | null; // String
    type_of_visit: string | null; // String
    uuid: string | null; // String
    violence_referred: string | null; // String
    violence_results: string | null; // String
    violence_screened: string | null; // String
    violence_text: string | null; // String
    violence_treated: string | null; // String
    visit_date: string | null; // String
    visit_id: number | null; // Int
    visit_reason: string | null; // String
    vl_results: string | null; // String
    vl_test_done: string | null; // String
    voided: number | null; // Int
  }
  ContactsLinked: { // field return type
    baseline_hiv_status: string | null; // String
    final_test_result: string | null; // String
    patient_id: number | null; // Int
    relationship_type: number | null; // Int
    visit_date: string | null; // String
  }
  Covid19Assessment: { // field return type
    admission_unit: string | null; // String
    booster_dose_verified: string | null; // String
    booster_sequence: string | null; // String
    booster_vaccine_taken: string | null; // String
    date_created: string | null; // String
    date_last_modified: string | null; // String
    date_taken_booster_vaccine: string | null; // String
    date_tested_positive: string | null; // String
    encounter_id: number | null; // Int
    ever_received_booster: string | null; // String
    ever_tested_covid_19_positive: string | null; // String
    ever_vaccinated: string | null; // String
    final_vaccination_status: string | null; // String
    first_dose: string | null; // String
    first_dose_date: string | null; // String
    first_vaccination_verified: string | null; // String
    first_vaccine_type: string | null; // String
    hospital_admission: string | null; // String
    location_id: number | null; // Int
    mfl_code: number | null; // Int
    obs_id: string | null; // String
    on_oxygen_supplement: string | null; // String
    on_ventillator: string | null; // String
    patient_id: number | null; // Int
    provider: number | null; // Int
    second_dose: string | null; // String
    second_dose_date: string | null; // String
    second_vaccination_verified: string | null; // String
    second_vaccine_type: string | null; // String
    symptomatic: string | null; // String
    uuid: string | null; // String
    visit_date: string | null; // String
    visit_id: number | null; // Int
    voided: number | null; // Int
  }
  ETLHtsTest: { // field return type
    approach: string; // String!
    client_tested_as: string; // String!
    couple_discordant: string; // String!
    creator: string; // String!
    date_created: string; // String!
    date_last_modified: string; // String!
    disability_type: string; // String!
    encounter_id: number; // Int!
    encounter_location: number; // Int!
    encounter_uuid: string; // String!
    ever_tested_for_hiv: string; // String!
    final_test_result: string; // String!
    fml_code: number; // Int!
    hts_entry_point: string; // String!
    id: number; // Int!
    months_since_last_test: string; // String!
    neg_referral_for: string; // String!
    neg_referral_specify: string; // String!
    other_referral_facility: string; // String!
    patient_consented: string; // String!
    patient_disabled: string; // String!
    patient_given_result: string; // String!
    patient_had_hiv_self_test: string; // String!
    patient_id: number; // Int!
    population_type: string; // String!
    referral_facility: string; // String!
    referral_for: string; // String!
    remarks: string; // String!
    setting: string; // String!
    syphillis_test_result: string; // String!
    tb_screening: string; // String!
    test_1_kit_expiry: string; // String!
    test_1_kit_lot_no: string; // String!
    test_1_kit_name: string; // String!
    test_1_result: string; // String!
    test_2_kit_expiry: string; // String!
    test_2_kit_lot_no: string; // String!
    test_2_kit_name: string; // String!
    test_2_result: string; // String!
    test_strategy: string; // String!
    test_type: string; // String!
    visit_date: string; // String!
    visit_id: number; // Int!
    voided: string; // String!
  }
  EtlCurrentInCare: { // field return type
    date_discontinued: string | null; // String
    disc_patient: string | null; // String
    dob: string | null; // String
    effective_disc_date: string | null; // String
    enroll_date: string | null; // String
    gender: string | null; // String
    latest_enrolment_date: string | null; // String
    latest_tca: string | null; // String
    latest_vis_date: string | null; // String
    mfl_code: number | null; // Int
    patient_id: number | null; // Int
    stability: string | null; // String
    started_on_drugs: number | null; // Int
  }
  EtlPatientProgram: { // field return type
    date_completed: string; // String!
    date_created: string; // String!
    date_enrolled: string; // String!
    date_last_modified: string; // String!
    fml_code: number; // Int!
    id: number; // Int!
    location_id: number; // Int!
    outcome: string; // String!
    patient_id: number; // Int!
    program: string; // String!
    uuid: string; // String!
    voided: string; // String!
  }
  Mutation: { // field return type
    postARTPreparation: NexusGenRootTypes['ARTPreparation']; // ARTPreparation!
    postAdverseEvents: NexusGenRootTypes['AdverseEvents']; // AdverseEvents!
    postAlcoholDrugAbuseScreening: NexusGenRootTypes['AlcoholDrugAbuseScreening'] | null; // AlcoholDrugAbuseScreening
    postAllergyChronicIllness: NexusGenRootTypes['AllergyChronicIllness']; // AllergyChronicIllness!
    postCccDefaulterTracing: NexusGenRootTypes['CccDefaulterTracing']; // CccDefaulterTracing!
    postCervicalCancerScreening: NexusGenRootTypes['CervicalCancerScreening']; // CervicalCancerScreening!
    postClientEnrollment: NexusGenRootTypes['ClientEnrollment']; // ClientEnrollment!
    postClientTrace: NexusGenRootTypes['ClientTrace']; // ClientTrace!
    postClinicalVisit: NexusGenRootTypes['ClinicalVisit']; // ClinicalVisit!
    postContactsLinked: NexusGenRootTypes['ContactsLinked']; // ContactsLinked!
    postCovid19Assessment: NexusGenRootTypes['Covid19Assessment']; // Covid19Assessment!
    postCurrentInCare: NexusGenRootTypes['EtlCurrentInCare'] | null; // EtlCurrentInCare
    postHtsTest: NexusGenRootTypes['ETLHtsTest']; // ETLHtsTest!
    postProgram: NexusGenRootTypes['EtlPatientProgram']; // EtlPatientProgram!
  }
  Query: { // field return type
    get: NexusGenRootTypes['EtlPatientProgram'][]; // [EtlPatientProgram!]!
    getHtsTest: NexusGenRootTypes['ETLHtsTest'][]; // [ETLHtsTest!]!
  }
}

export interface NexusGenFieldTypeNames {
  ARTPreparation: { // field return type name
    HIV_status_disclosure: 'String'
    adherance_barriers_identified: 'String'
    caregiver_location_contacts_known: 'String'
    date_created: 'Int'
    date_last_modified: 'Int'
    encounter_id: 'Int'
    enrolled_in_reminder_system: 'String'
    identified_drug_time: 'String'
    informed_drug_side_effects: 'String'
    location_id: 'Int'
    mfl_code: 'Int'
    other_support_systems: 'String'
    patient_id: 'Int'
    provider: 'Int'
    ready_to_start_art: 'String'
    screened_negative_psychiatric_illness: 'String'
    screened_negative_substance_abuse: 'String'
    support_grp_meeting_awareness: 'String'
    trained_drug_admin: 'String'
    treatment_supporter_engaged: 'String'
    understands_hiv_art_benefits: 'String'
    uuid: 'String'
    visit_date: 'String'
    visit_id: 'Int'
    voided: 'Int'
  }
  AdverseEvents: { // field return type name
    adverse_event: 'Int'
    cause: 'Int'
    date_created: 'Int'
    date_last_modified: 'Int'
    encounter_id: 'Int'
    form: 'String'
    location_id: 'Int'
    mfl_code: 'Int'
    obs_id: 'Int'
    patient_id: 'Int'
    provider: 'Int'
    severity: 'Int'
    start_date: 'String'
    uuid: 'String'
    visit_date: 'String'
    visit_id: 'Int'
    voided: 'Int'
  }
  AlcoholDrugAbuseScreening: { // field return type name
    alcohol_drinking_frequency: 'String'
    date_created: 'Int'
    date_last_modified: 'Int'
    drugs_use_frequency: 'String'
    encounter_id: 'Int'
    location_id: 'Int'
    mfl_code: 'Int'
    patient_id: 'Int'
    provider: 'Int'
    smoking_frequency: 'String'
    uuid: 'String'
    visit_date: 'String'
    visit_id: 'Int'
    voided: 'Int'
  }
  AllergyChronicIllness: { // field return type name
    allergy_causative_agent: 'String'
    allergy_onset_date: 'String'
    allergy_reaction: 'Int'
    allergy_severity: 'Int'
    chronic_illness: 'Int'
    chronic_illness_onset_date: 'String'
    date_created: 'Int'
    date_last_modified: 'Int'
    encounter_id: 'Int'
    location_id: 'Int'
    mfl_code: 'Int'
    obs_id: 'Int'
    patient_id: 'Int'
    provider: 'Int'
    uuid: 'String'
    visit_date: 'String'
    visit_id: 'Int'
    voided: 'Int'
  }
  CccDefaulterTracing: { // field return type name
    attempt_number: 'Int'
    booking_date: 'String'
    cause_of_death: 'Int'
    comments: 'String'
    date_created: 'Int'
    date_last_modified: 'Int'
    encounter_id: 'Int'
    fml_code: 'Int'
    is_final_trace: 'Int'
    location_id: 'Int'
    mfl_code: 'Int'
    non_coded_missed_appointment_reason: 'String'
    patient_id: 'Int'
    provider: 'Int'
    reason_for_missed_appointment: 'Int'
    tracing_outcome: 'Int'
    tracing_type: 'Int'
    true_status: 'Int'
    uuid: 'String'
    visit_date: 'String'
    visit_id: 'Int'
  }
  CervicalCancerScreening: { // field return type name
    booking_date: 'String'
    date_last_modified: 'String'
    encounter_id: 'Int'
    encounter_provider: 'Int'
    location_id: 'Int'
    mfl_code: 'Int'
    patient_id: 'Int'
    post_treatment_complication_cause: 'String'
    provider: 'Int'
    referral_facility: 'String'
    referral_reason: 'String'
    referred_out: 'String'
    screening_method: 'String'
    screening_result: 'String'
    screening_type: 'String'
    treatment_method: 'String'
    treatment_method_other: 'String'
    uuid: 'String'
    visit_date: 'String'
    visit_id: 'Int'
    visit_type: 'String'
    voided: 'Int'
  }
  ClientEnrollment: { // field return type name
    buddy_name: 'String'
    buddy_phone_number: 'String'
    care_facility_name: 'String'
    ccc_number: 'String'
    client_id: 'Int'
    contact_for_appointment: 'String'
    contact_method: 'String'
    contacted_for_prevention: 'String'
    date_last_modified: 'String'
    encounter_id: 'Int'
    encounter_provider: 'Int'
    ever_tested_for_hiv: 'String'
    fml_code: 'Int'
    has_expereienced_physical_violence: 'String'
    has_expereienced_sexual_violence: 'String'
    has_regular_free_sex_partner: 'String'
    location_id: 'Int'
    mfl_code: 'Int'
    receiving_hiv_care: 'String'
    share_test_results: 'String'
    test_decline_reason: 'String'
    test_type: 'String'
    uuid: 'String'
    visit_date: 'String'
    visit_id: 'Int'
    vl_results_date: 'String'
    vl_test_done: 'String'
    voided: 'Int'
    willing_to_test: 'String'
    year_started_drugs: 'String'
    year_started_sex_with_men: 'String'
  }
  ClientTrace: { // field return type name
    appointment_date: 'Int'
    client_id: 'Int'
    contact_type: 'String'
    date_created: 'Int'
    date_last_modified: 'Int'
    encounter_date: 'String'
    facility_linked_to: 'Int'
    health_worker_handed_to: 'String'
    mfl_code: 'Int'
    remarks: 'Int'
    status: 'String'
    unique_patient_no: 'String'
    uuid: 'String'
  }
  ClinicalVisit: { // field return type name
    abscess_referred: 'String'
    abscess_results: 'String'
    abscess_screened: 'String'
    abscess_text: 'String'
    abscess_treated: 'String'
    active_art: 'String'
    alcohol_referred: 'String'
    alcohol_results: 'String'
    alcohol_screened: 'String'
    alcohol_text: 'String'
    alcohol_treated: 'String'
    appointment_date: 'String'
    cerv_cancer_referred: 'String'
    cerv_cancer_results: 'String'
    cerv_cancer_screened: 'String'
    cerv_cancer_text: 'String'
    cerv_cancer_treated: 'String'
    client_id: 'Int'
    clinical_notes: 'String'
    condom_use_education: 'String'
    confirmatory_facility: 'String'
    counselled_for_hiv: 'String'
    date_created: 'String'
    date_last_modified: 'String'
    distribution_kits: 'String'
    eligible_vl: 'String'
    encounter_id: 'Int'
    encounter_provider: 'Int'
    exposure_type: 'String'
    facility_linked_to: 'String'
    female_condoms_no: 'String'
    fp_eligibility: 'String'
    fp_referred: 'String'
    fp_screened: 'String'
    fp_text: 'String'
    fp_treated: 'String'
    hepatitisB_referred: 'String'
    hepatitisB_results: 'String'
    hepatitisB_screened: 'String'
    hepatitisB_text: 'String'
    hepatitisB_treated: 'String'
    hepatitisC_referred: 'String'
    hepatitisC_results: 'String'
    hepatitisC_screened: 'String'
    hepatitisC_text: 'String'
    hepatitisC_treated: 'String'
    hiv_care_facility: 'String'
    hiv_self_rep_status: 'String'
    hiv_tested: 'String'
    implementing_partner: 'String'
    initiated_art_this_month: 'String'
    last_hiv_test_setting: 'String'
    linked_to_art: 'String'
    linked_to_psychosocial: 'String'
    location_id: 'Int'
    lubes_no: 'String'
    male_condoms_no: 'String'
    mental_health_referred: 'String'
    mental_health_results: 'String'
    mental_health_screened: 'String'
    mental_health_support: 'String'
    mental_health_text: 'String'
    mfl_code: 'Int'
    offsite_confirmatory_facility: 'String'
    other_exposure_type: 'String'
    other_hiv_care_facility: 'String'
    overdose_referred: 'String'
    overdose_results: 'String'
    overdose_screened: 'String'
    overdose_text: 'String'
    overdose_treated: 'String'
    pep_eligible: 'String'
    post_abortal_care: 'String'
    prep_referred: 'String'
    prep_results: 'String'
    prep_screened: 'String'
    prep_text: 'String'
    prep_treated: 'String'
    received_naloxone: 'String'
    received_results: 'String'
    received_vl_results: 'String'
    risk_red_counselling_ebi_provided: 'String'
    risk_red_counselling_eligibility: 'String'
    risk_red_counselling_screened: 'String'
    risk_red_counselling_support: 'String'
    risk_red_counselling_text: 'String'
    self_test_date: 'String'
    self_test_education: 'String'
    self_test_frequency: 'String'
    self_test_kits_given: 'String'
    self_test_link_facility: 'String'
    self_test_linked_art: 'String'
    self_test_results: 'String'
    self_tested: 'String'
    self_use_kits: 'String'
    service_delivery_model: 'String'
    sti_referred: 'String'
    sti_referred_text: 'String'
    sti_results: 'String'
    sti_screened: 'String'
    sti_treated: 'String'
    syringes_needles_no: 'String'
    tb_referred: 'String'
    tb_referred_text: 'String'
    tb_results: 'String'
    tb_screened: 'String'
    tb_treated: 'String'
    test_confirmatory_results: 'String'
    test_frequency: 'String'
    test_results: 'String'
    type_of_visit: 'String'
    uuid: 'String'
    violence_referred: 'String'
    violence_results: 'String'
    violence_screened: 'String'
    violence_text: 'String'
    violence_treated: 'String'
    visit_date: 'String'
    visit_id: 'Int'
    visit_reason: 'String'
    vl_results: 'String'
    vl_test_done: 'String'
    voided: 'Int'
  }
  ContactsLinked: { // field return type name
    baseline_hiv_status: 'String'
    final_test_result: 'String'
    patient_id: 'Int'
    relationship_type: 'Int'
    visit_date: 'String'
  }
  Covid19Assessment: { // field return type name
    admission_unit: 'String'
    booster_dose_verified: 'String'
    booster_sequence: 'String'
    booster_vaccine_taken: 'String'
    date_created: 'String'
    date_last_modified: 'String'
    date_taken_booster_vaccine: 'String'
    date_tested_positive: 'String'
    encounter_id: 'Int'
    ever_received_booster: 'String'
    ever_tested_covid_19_positive: 'String'
    ever_vaccinated: 'String'
    final_vaccination_status: 'String'
    first_dose: 'String'
    first_dose_date: 'String'
    first_vaccination_verified: 'String'
    first_vaccine_type: 'String'
    hospital_admission: 'String'
    location_id: 'Int'
    mfl_code: 'Int'
    obs_id: 'String'
    on_oxygen_supplement: 'String'
    on_ventillator: 'String'
    patient_id: 'Int'
    provider: 'Int'
    second_dose: 'String'
    second_dose_date: 'String'
    second_vaccination_verified: 'String'
    second_vaccine_type: 'String'
    symptomatic: 'String'
    uuid: 'String'
    visit_date: 'String'
    visit_id: 'Int'
    voided: 'Int'
  }
  ETLHtsTest: { // field return type name
    approach: 'String'
    client_tested_as: 'String'
    couple_discordant: 'String'
    creator: 'String'
    date_created: 'String'
    date_last_modified: 'String'
    disability_type: 'String'
    encounter_id: 'Int'
    encounter_location: 'Int'
    encounter_uuid: 'String'
    ever_tested_for_hiv: 'String'
    final_test_result: 'String'
    fml_code: 'Int'
    hts_entry_point: 'String'
    id: 'Int'
    months_since_last_test: 'String'
    neg_referral_for: 'String'
    neg_referral_specify: 'String'
    other_referral_facility: 'String'
    patient_consented: 'String'
    patient_disabled: 'String'
    patient_given_result: 'String'
    patient_had_hiv_self_test: 'String'
    patient_id: 'Int'
    population_type: 'String'
    referral_facility: 'String'
    referral_for: 'String'
    remarks: 'String'
    setting: 'String'
    syphillis_test_result: 'String'
    tb_screening: 'String'
    test_1_kit_expiry: 'String'
    test_1_kit_lot_no: 'String'
    test_1_kit_name: 'String'
    test_1_result: 'String'
    test_2_kit_expiry: 'String'
    test_2_kit_lot_no: 'String'
    test_2_kit_name: 'String'
    test_2_result: 'String'
    test_strategy: 'String'
    test_type: 'String'
    visit_date: 'String'
    visit_id: 'Int'
    voided: 'String'
  }
  EtlCurrentInCare: { // field return type name
    date_discontinued: 'String'
    disc_patient: 'String'
    dob: 'String'
    effective_disc_date: 'String'
    enroll_date: 'String'
    gender: 'String'
    latest_enrolment_date: 'String'
    latest_tca: 'String'
    latest_vis_date: 'String'
    mfl_code: 'Int'
    patient_id: 'Int'
    stability: 'String'
    started_on_drugs: 'Int'
  }
  EtlPatientProgram: { // field return type name
    date_completed: 'String'
    date_created: 'String'
    date_enrolled: 'String'
    date_last_modified: 'String'
    fml_code: 'Int'
    id: 'Int'
    location_id: 'Int'
    outcome: 'String'
    patient_id: 'Int'
    program: 'String'
    uuid: 'String'
    voided: 'String'
  }
  Mutation: { // field return type name
    postARTPreparation: 'ARTPreparation'
    postAdverseEvents: 'AdverseEvents'
    postAlcoholDrugAbuseScreening: 'AlcoholDrugAbuseScreening'
    postAllergyChronicIllness: 'AllergyChronicIllness'
    postCccDefaulterTracing: 'CccDefaulterTracing'
    postCervicalCancerScreening: 'CervicalCancerScreening'
    postClientEnrollment: 'ClientEnrollment'
    postClientTrace: 'ClientTrace'
    postClinicalVisit: 'ClinicalVisit'
    postContactsLinked: 'ContactsLinked'
    postCovid19Assessment: 'Covid19Assessment'
    postCurrentInCare: 'EtlCurrentInCare'
    postHtsTest: 'ETLHtsTest'
    postProgram: 'EtlPatientProgram'
  }
  Query: { // field return type name
    get: 'EtlPatientProgram'
    getHtsTest: 'ETLHtsTest'
  }
}

export interface NexusGenArgTypes {
  Mutation: {
    postARTPreparation: { // args
      HIV_status_disclosure?: string | null; // String
      adherance_barriers_identified?: string | null; // String
      caregiver_committed?: string | null; // String
      caregiver_location_contacts_known?: string | null; // String
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      encounter_id?: number | null; // Int
      enrolled_in_reminder_system?: string | null; // String
      identified_drug_time?: string | null; // String
      informed_drug_side_effects?: string | null; // String
      location_id?: number | null; // Int
      mfl_code?: number | null; // Int
      other_support_systems?: string | null; // String
      patient_id?: number | null; // Int
      provider?: number | null; // Int
      ready_to_start_art?: string | null; // String
      screened_negative_psychiatric_illness?: string | null; // String
      screened_negative_substance_abuse?: string | null; // String
      support_grp_meeting_awareness?: string | null; // String
      trained_drug_admin?: string | null; // String
      treatment_supporter_engaged?: string | null; // String
      understands_hiv_art_benefits?: string | null; // String
      uuid?: string | null; // String
      visit_date?: string | null; // String
      visit_id?: number | null; // Int
    }
    postAdverseEvents: { // args
      action_taken?: number | null; // Int
      adverse_event?: number | null; // Int
      cause?: number | null; // Int
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      encounter_id?: number | null; // Int
      form?: string | null; // String
      location_id?: number | null; // Int
      mfl_code?: number | null; // Int
      obs_id?: number | null; // Int
      patient_id?: number | null; // Int
      provider?: number | null; // Int
      severity?: number | null; // Int
      start_date?: string | null; // String
      uuid?: string | null; // String
      visit_date?: string | null; // String
      visit_id?: number | null; // Int
      voided?: number | null; // Int
    }
    postAlcoholDrugAbuseScreening: { // args
      alcohol_drinking_frequency?: string | null; // String
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      drugs_use_frequency?: string | null; // String
      encounter_id?: number | null; // Int
      location_id?: number | null; // Int
      mfl_code?: number | null; // Int
      patient_id?: number | null; // Int
      provider?: number | null; // Int
      smoking_frequency?: string | null; // String
      uuid?: string | null; // String
      visit_date?: string | null; // String
      visit_id?: number | null; // Int
      voided?: number | null; // Int
    }
    postAllergyChronicIllness: { // args
      allergy_causative_agent?: number | null; // Int
      allergy_onset_date?: string | null; // String
      allergy_reaction?: number | null; // Int
      allergy_severity?: number | null; // Int
      chronic_illness?: number | null; // Int
      chronic_illness_onset_date?: string | null; // String
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      encounter_id?: number | null; // Int
      location_id?: number | null; // Int
      mfl_code?: number | null; // Int
      obs_id?: number | null; // Int
      patient_id?: number | null; // Int
      provider?: number | null; // Int
      uuid?: string | null; // String
      visit_date?: string | null; // String
      visit_id?: number | null; // Int
      voided?: number | null; // Int
    }
    postCccDefaulterTracing: { // args
      attempt_number?: number | null; // Int
      booking_date?: string | null; // String
      cause_of_death?: number | null; // Int
      comments?: string | null; // String
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      encounter_id?: number | null; // Int
      is_final_trace?: number | null; // Int
      location_id?: number | null; // Int
      mfl_code?: number | null; // Int
      non_coded_missed_appointment_reason?: string | null; // String
      patient_id?: number | null; // Int
      provider?: number | null; // Int
      reason_for_missed_appointment?: number | null; // Int
      tracing_outcome?: number | null; // Int
      tracing_type?: number | null; // Int
      true_status?: number | null; // Int
      uuid?: string | null; // String
      visit_date?: string | null; // String
      visit_id?: number | null; // Int
    }
    postCervicalCancerScreening: { // args
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      encounter_id?: number | null; // Int
      encounter_provider?: number | null; // Int
      location_id?: number | null; // Int
      mfl_code?: number | null; // Int
      next_appointment_date?: string | null; // String
      patient_id?: number | null; // Int
      post_treatment_complication_cause?: string | null; // String
      post_treatment_complication_other?: string | null; // String
      referral_facility?: string | null; // String
      referral_reason?: string | null; // String
      referred_out?: string | null; // String
      screening_method?: string | null; // String
      screening_result?: string | null; // String
      screening_type?: string | null; // String
      treatment_method?: string | null; // String
      treatment_method_other?: string | null; // String
      uuid?: string | null; // String
      visit_date?: string | null; // String
      visit_id?: number | null; // Int
      visit_type?: string | null; // String
      voided?: number | null; // Int
    }
    postClientEnrollment: { // args
      buddy_name?: string | null; // String
      buddy_phone_number?: string | null; // String
      care_facility_name?: string | null; // String
      ccc_number?: string | null; // String
      client_id?: number | null; // Int
      contact_for_appointment?: string | null; // String
      contact_method?: string | null; // String
      contacted_for_prevention?: string | null; // String
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      encounter_id?: number | null; // Int
      encounter_provider?: number | null; // Int
      ever_tested_for_hiv?: string | null; // String
      has_expereienced_physical_violence?: string | null; // String
      has_expereienced_sexual_violence?: string | null; // String
      has_regular_free_sex_partner?: string | null; // String
      mfl_code?: number | null; // Int
      receiving_hiv_care?: string | null; // String
      share_test_results?: string | null; // String
      test_decline_reason?: string | null; // String
      test_type?: string | null; // String
      uuid?: string | null; // String
      visit_date?: string | null; // String
      visit_id?: number | null; // Int
      vl_results_date?: string | null; // String
      vl_test_done?: string | null; // String
      voided?: number | null; // Int
      willing_to_test?: string | null; // String
      year_started_drugs?: string | null; // String
      year_started_sex_with_men?: string | null; // String
      year_started_sex_work?: string | null; // String
    }
    postClientTrace: { // args
      appointment_date?: string | null; // String
      client_id?: number | null; // Int
      contact_type?: string | null; // String
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      encounter_date?: string | null; // String
      facility_linked_to?: string | null; // String
      health_worker_handed_to?: string | null; // String
      mfl_code?: number | null; // Int
      remarks?: string | null; // String
      status?: string | null; // String
      unique_patient_no?: string | null; // String
      uuid?: string | null; // String
      voided?: string | null; // String
    }
    postClinicalVisit: { // args
      abscess_referred?: string | null; // String
      abscess_results?: string | null; // String
      abscess_screened?: string | null; // String
      abscess_text?: string | null; // String
      abscess_treated?: string | null; // String
      active_art?: string | null; // String
      alcohol_referred?: string | null; // String
      alcohol_results?: string | null; // String
      alcohol_screened?: string | null; // String
      alcohol_text?: string | null; // String
      alcohol_treated?: string | null; // String
      appointment_date?: string | null; // String
      cerv_cancer_referred?: string | null; // String
      cerv_cancer_results?: string | null; // String
      cerv_cancer_screened?: string | null; // String
      cerv_cancer_text?: string | null; // String
      cerv_cancer_treated?: string | null; // String
      client_id?: number | null; // Int
      clinical_notes?: string | null; // String
      condom_use_education?: string | null; // String
      confirmatory_facility?: string | null; // String
      counselled_for_hiv?: string | null; // String
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      distribution_kits?: string | null; // String
      eligible_vl?: string | null; // String
      encounter_id?: number | null; // Int
      encounter_provider?: number | null; // Int
      exposure_type?: string | null; // String
      facility_linked_to?: string | null; // String
      female_condoms_no?: string | null; // String
      fp_eligibility?: string | null; // String
      fp_referred?: string | null; // String
      fp_screened?: string | null; // String
      fp_text?: string | null; // String
      fp_treated?: string | null; // String
      hepatitisB_referred?: string | null; // String
      hepatitisB_results?: string | null; // String
      hepatitisB_screened?: string | null; // String
      hepatitisB_text?: string | null; // String
      hepatitisB_treated?: string | null; // String
      hepatitisC_referred?: string | null; // String
      hepatitisC_results?: string | null; // String
      hepatitisC_screened?: string | null; // String
      hepatitisC_text?: string | null; // String
      hepatitisC_treated?: string | null; // String
      hiv_care_facility?: string | null; // String
      hiv_self_rep_status?: string | null; // String
      hiv_tested?: string | null; // String
      implementing_partner?: string | null; // String
      initiated_art_this_month?: string | null; // String
      last_hiv_test_setting?: string | null; // String
      linked_to_art?: string | null; // String
      linked_to_psychosocial?: string | null; // String
      location_id?: number | null; // Int
      lubes_no?: string | null; // String
      male_condoms_no?: string | null; // String
      mental_health_referred?: string | null; // String
      mental_health_results?: string | null; // String
      mental_health_screened?: string | null; // String
      mental_health_support?: string | null; // String
      mental_health_text?: string | null; // String
      mfl_code?: number | null; // Int
      offsite_confirmatory_facility?: string | null; // String
      other_exposure_type?: string | null; // String
      other_hiv_care_facility?: string | null; // String
      overdose_referred?: string | null; // String
      overdose_results?: string | null; // String
      overdose_screened?: string | null; // String
      overdose_text?: string | null; // String
      overdose_treated?: string | null; // String
      pep_eligible?: string | null; // String
      post_abortal_care?: string | null; // String
      prep_referred?: string | null; // String
      prep_results?: string | null; // String
      prep_screened?: string | null; // String
      prep_text?: string | null; // String
      prep_treated?: string | null; // String
      received_naloxone?: string | null; // String
      received_results?: string | null; // String
      received_vl_results?: string | null; // String
      risk_red_counselling_ebi_provided?: string | null; // String
      risk_red_counselling_eligibility?: string | null; // String
      risk_red_counselling_screened?: string | null; // String
      risk_red_counselling_support?: string | null; // String
      risk_red_counselling_text?: string | null; // String
      self_test_date?: string | null; // String
      self_test_education?: string | null; // String
      self_test_frequency?: string | null; // String
      self_test_kits_given?: string | null; // String
      self_test_link_facility?: string | null; // String
      self_test_linked_art?: string | null; // String
      self_test_results?: string | null; // String
      self_tested?: string | null; // String
      self_use_kits?: string | null; // String
      service_delivery_model?: string | null; // String
      sti_referred?: string | null; // String
      sti_referred_text?: string | null; // String
      sti_results?: string | null; // String
      sti_screened?: string | null; // String
      sti_treated?: string | null; // String
      syringes_needles_no?: string | null; // String
      tb_referred?: string | null; // String
      tb_referred_text?: string | null; // String
      tb_results?: string | null; // String
      tb_screened?: string | null; // String
      tb_treated?: string | null; // String
      test_confirmatory_results?: string | null; // String
      test_frequency?: string | null; // String
      test_results?: string | null; // String
      type_of_visit?: string | null; // String
      uuid?: string | null; // String
      violence_referred?: string | null; // String
      violence_results?: string | null; // String
      violence_screened?: string | null; // String
      violence_text?: string | null; // String
      violence_treated?: string | null; // String
      visit_date?: string | null; // String
      visit_id?: number | null; // Int
      visit_reason?: string | null; // String
      vl_results?: string | null; // String
      vl_test_done?: string | null; // String
      voided?: number | null; // Int
    }
    postContactsLinked: { // args
      baseline_hiv_status?: string | null; // String
      final_test_result?: string | null; // String
      mfl_code?: number | null; // Int
      patient_id?: number | null; // Int
      relationship_type?: number | null; // Int
      visit_date?: string | null; // String
    }
    postCovid19Assessment: { // args
      baseline_hiv_status?: string | null; // String
      final_test_result?: string | null; // String
      mfl_code?: number | null; // Int
      patient_id?: number | null; // Int
      relationship_type?: number | null; // Int
      visit_date?: string | null; // String
    }
    postCurrentInCare: { // args
      date_discontinued?: string | null; // String
      disc_patient?: string | null; // String
      dob?: string | null; // String
      effective_disc_date?: string | null; // String
      enroll_date?: string | null; // String
      gender?: string | null; // String
      latest_enrolment_date?: string | null; // String
      latest_tca?: string | null; // String
      latest_vis_date?: string | null; // String
      mfl_code?: number | null; // Int
      patient_id?: number | null; // Int
      stability?: string | null; // String
      started_on_drugs?: number | null; // Int
    }
    postHtsTest: { // args
      approach?: string | null; // String
      client_tested_as?: string | null; // String
      couple_discordant?: string | null; // String
      creator?: string | null; // String
      date_created?: string | null; // String
      date_last_modified?: string | null; // String
      disability_type?: string | null; // String
      encounter_id: number; // Int!
      encounter_location?: number | null; // Int
      encounter_uuid: string; // String!
      ever_tested_for_hiv?: string | null; // String
      final_test_result?: string | null; // String
      fml_code: number; // Int!
      hts_entry_point?: string | null; // String
      key_population_type?: string | null; // String
      months_since_last_test?: string | null; // String
      neg_referral_for?: string | null; // String
      neg_referral_specify?: string | null; // String
      other_referral_facility?: string | null; // String
      patient_consented?: string | null; // String
      patient_disabled?: string | null; // String
      patient_given_result?: string | null; // String
      patient_had_hiv_self_test?: string | null; // String
      patient_id: number; // Int!
      population_type?: string | null; // String
      referral_facility?: string | null; // String
      referral_for?: string | null; // String
      remarks?: string | null; // String
      setting?: string | null; // String
      syphillis_test_result?: string | null; // String
      tb_screening?: string | null; // String
      test_1_kit_expiry?: string | null; // String
      test_1_kit_lot_no?: string | null; // String
      test_1_kit_name?: string | null; // String
      test_1_result?: string | null; // String
      test_2_kit_expiry?: string | null; // String
      test_2_kit_lot_no?: string | null; // String
      test_2_kit_name?: string | null; // String
      test_2_result?: string | null; // String
      test_strategy?: string | null; // String
      test_type?: string | null; // String
      visit_date?: string | null; // String
      visit_id: number; // Int!
      voided?: string | null; // String
    }
    postProgram: { // args
      date_completed?: string | null; // String
      date_created?: string | null; // String
      date_enrolled?: string | null; // String
      date_last_modified?: string | null; // String
      date_modified?: string | null; // String
      fml_code?: number | null; // Int
      location_id?: number | null; // Int
      outcome?: string | null; // String
      patient_id: number; // Int!
      program?: string | null; // String
      uuid: string; // String!
      voided?: string | null; // String
    }
  }
}

export interface NexusGenAbstractTypeMembers {
}

export interface NexusGenTypeInterfaces {
}

export type NexusGenObjectNames = keyof NexusGenObjects;

export type NexusGenInputNames = never;

export type NexusGenEnumNames = never;

export type NexusGenInterfaceNames = never;

export type NexusGenScalarNames = keyof NexusGenScalars;

export type NexusGenUnionNames = never;

export type NexusGenObjectsUsingAbstractStrategyIsTypeOf = never;

export type NexusGenAbstractsUsingStrategyResolveType = never;

export type NexusGenFeaturesConfig = {
  abstractTypeStrategies: {
    isTypeOf: false
    resolveType: true
    __typename: false
  }
}

export interface NexusGenTypes {
  context: Context;
  inputTypes: NexusGenInputs;
  rootTypes: NexusGenRootTypes;
  inputTypeShapes: NexusGenInputs & NexusGenEnums & NexusGenScalars;
  argTypes: NexusGenArgTypes;
  fieldTypes: NexusGenFieldTypes;
  fieldTypeNames: NexusGenFieldTypeNames;
  allTypes: NexusGenAllTypes;
  typeInterfaces: NexusGenTypeInterfaces;
  objectNames: NexusGenObjectNames;
  inputNames: NexusGenInputNames;
  enumNames: NexusGenEnumNames;
  interfaceNames: NexusGenInterfaceNames;
  scalarNames: NexusGenScalarNames;
  unionNames: NexusGenUnionNames;
  allInputTypes: NexusGenTypes['inputNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['scalarNames'];
  allOutputTypes: NexusGenTypes['objectNames'] | NexusGenTypes['enumNames'] | NexusGenTypes['unionNames'] | NexusGenTypes['interfaceNames'] | NexusGenTypes['scalarNames'];
  allNamedTypes: NexusGenTypes['allInputTypes'] | NexusGenTypes['allOutputTypes']
  abstractTypes: NexusGenTypes['interfaceNames'] | NexusGenTypes['unionNames'];
  abstractTypeMembers: NexusGenAbstractTypeMembers;
  objectsUsingAbstractStrategyIsTypeOf: NexusGenObjectsUsingAbstractStrategyIsTypeOf;
  abstractsUsingStrategyResolveType: NexusGenAbstractsUsingStrategyResolveType;
  features: NexusGenFeaturesConfig;
}


declare global {
  interface NexusGenPluginTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginInputTypeConfig<TypeName extends string> {
  }
  interface NexusGenPluginFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginInputFieldConfig<TypeName extends string, FieldName extends string> {
  }
  interface NexusGenPluginSchemaConfig {
  }
  interface NexusGenPluginArgConfig {
  }
}